title: Document Hasher
description: This Add-On allows you to calculate the SHA-1 hash of a document and add it to the document as a key value pair to establish authenticity of primary source material. 
type: object
documents:
  - query
  - selected
properties: {}
categories:
  - extraction
version: 2
